apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayk8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayk8s
  template:
    metadata:
      labels:
        app: gatewayk8s
    spec:
      containers:
      - image: gateway:14.18
        imagePullPolicy: IfNotPresent
        name: gatewayk8s
        ports:
        - containerPort: 8080
