apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-k8s
  template:
    metadata:
      labels:
        app: gateway-k8s
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        image: gateway:18.112
        auth:
          username: dgoalmeida
          password: @Dac@413@
        imagePullPolicy: Always
        name: gateway-k8s
        ports:
        - containerPort: 8080
