spring:
  cloud:
    gateway:
      routes:
        - id: health
          uri: http://rabbitmq-producer-k8s-svc:8081
          predicates:
            - Path= /health
        - id: test
          uri: http://rabbitmq-producer-k8s-svc:8081
          predicates:
            - Path= /hello
            - Header=X-Request-Id, \d+
            - Query=param
            - Cookie=cookie1, \d+