spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: health
          uri: http://rabbitmq-producer-k8s-svc:8080
          predicates:
            - Path= /health
        - id: test
          uri: http://rabbitmq-producer-k8s-svc:8080
          predicates:
            - Path= /hello
            - Header=X-Request-Id, \d+
            - Query=param
            - Cookie=cookie1, \d+
logging:
  pattern:
    level: '%clr(%5p) %clr([traceid=%X{traceId:-} spanid=%X{spanId:-} parentspanid=%X{parentId:-}]){green}'
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      enabled: true
  traces:
    sampler: 1.0
  propagation: tracecontext,baggage

