spring:
  application:
    name: gateway
  profiles:
    active: dev
logging:
  pattern:
    level: '%clr(%5p) %clr([traceid=%X{traceId:-} spanid=%X{spanId:-} parentspanid=%X{parentId:-}]){green}'
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      enabled: true
  traces:
    sampler: 1.0
  propagation: tracecontext,baggage

